### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [DWilliames/nudge-corner-radius#1]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by jeffebauer** [comment]
Following up on this issue. This was a super-useful plugin that I used on a daily basis, and would love to see it updated for recent versions of Sketch.

**Comment by DWilliames** [comment]
Sorry for the insane delay 🙈 
All fixed now and should be working on the latest Sketch versions now
