### ISSUE TITLE
Doesn't work with Sketch 52

### ISSUE THREAD

**Issue by andyra** [DWilliames/nudge-corner-radius#4]
Any chance this could be updated to support the latest version of Sketch (52)?

**Comment by DWilliames** [comment]
Just released a fix.
Thanks for suggesting it. I wasn't sure if anyone was still using this plugin :P 

I also fixed it so that you can nudge the radius of selected points when editing a shape too.

**Comment by andyra** [comment]
I use this plugin constantly! Thanks for making the improvements.
